# https://developers.google.com/wallet/reference/rest/v1/Media returns 404
# https://walletobjects.googleapis.com/$discovery/rest?version=v1
# This also appears to match the schema:
# https://docs.cloud.google.com/chronicle/docs/reference/rest/v1alpha/Media

from enum import Enum
from typing import Annotated, Optional

from pydantic import BaseModel, Field
from typing_extensions import deprecated


class MediaReferenceType(str, Enum):
    PATH = "PATH"
    """
    Reference contains a GFS path or a local path.
    """

    BLOB_REF = "BLOB_REF"
    """
    Reference points to a blobstore object. This could be either a v1 blob_ref
    or a v2 blobstore2_info. Clients should check blobstore2_info first, since
    v1 is being deprecated.
    """

    INLINE = "INLINE"
    """
    Data is included into this proto buffer
    """

    GET_MEDIA = "GET_MEDIA"
    """
    Data should be accessed from the current service using the operation
    GetMedia.
    """

    COMPOSITE_MEDIA = "COMPOSITE_MEDIA"
    """
    The content for this media object is stored across multiple partial media
    objects under the composite_media field.
    """

    BIGSTORE_REF = "BIGSTORE_REF"
    """
    Reference points to a bigstore object
    """

    DIFF_VERSION_RESPONSE = "DIFF_VERSION_RESPONSE"
    """
    Indicates the data is stored in diff_version_response.
    """

    DIFF_CHECKSUMS_RESPONSE = "DIFF_CHECKSUMS_RESPONSE"
    """
    Indicates the data is stored in diff_checksums_response.
    """

    DIFF_DOWNLOAD_RESPONSE = "DIFF_DOWNLOAD_RESPONSE"
    """
    Indicates the data is stored in diff_download_response.
    """

    DIFF_UPLOAD_REQUEST = "DIFF_UPLOAD_REQUEST"
    """
    Indicates the data is stored in diff_upload_request.
    """

    DIFF_UPLOAD_RESPONSE = "DIFF_UPLOAD_RESPONSE"
    """
    Indicates the data is stored in diff_upload_response.
    """

    COSMO_BINARY_REFERENCE = "COSMO_BINARY_REFERENCE"
    """
    Indicates the data is stored in cosmo_binary_reference.
    """

    ARBITRARY_BYTES = "ARBITRARY_BYTES"
    """
    Informs Scotty to generate a response payload with the size specified in
    the length field. The contents of the payload are generated by Scotty and
    are undefined. This is useful for testing download speeds between the user
    and Scotty without involving a real payload source. Note: range is not
    supported when using arbitrary_bytes.
    """


class Blobstore2Info(BaseModel):
    """
    Information to read/write to blobstore2.
    """

    uploadFragmentListCreationInfo: Optional[bytes] = None
    """
    A serialized Object Fragment List Creation Info passed from Bigstore ->
    Scotty for a GCS upload. This field must never be consumed outside of
    Bigstore, and is not applicable to non-GCS media uploads.
    """

    blobGeneration: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    The blob generation id.
    """

    blobId: Optional[str] = None
    """
    The blob id, e.g., /blobstore/prod/playground/scotty
    """

    readToken: Optional[str] = None
    """
    The blob read token. Needed to read blobs that have not been replicated.
    Might not be available until the final call.
    """

    downloadReadHandle: Optional[bytes] = None
    """
    Read handle passed from Bigstore -> Scotty for a GCS download. This is a
    signed, serialized blobstore2.ReadHandle proto which must never be set
    outside of Bigstore, and is not applicable to non-GCS media downloads.
    """

    downloadExternalReadToken: Optional[bytes] = None
    """
    A serialized External Read Token passed from Bigstore -> Scotty for a GCS
    download. This field must never be consumed outside of Bigstore, and is not
    applicable to non-GCS media uploads.
    """

    uploadMetadataContainer: Optional[bytes] = None
    """
    Metadata passed from Blobstore -> Scotty for a new GCS upload. This is a
    signed, serialized blobstore2.BlobMetadataContainer proto which must never
    be consumed outside of Bigstore, and is not applicable to non-GCS media
    uploads.
    """


class CompositeMediaReferenceType(str, Enum):
    PATH = "PATH"
    """
    Reference contains a GFS path or a local path.
    """

    BLOB_REF = "BLOB_REF"
    """
    Reference points to a blobstore object. This could be either a v1 blob_ref
    or a v2 blobstore2_info. Clients should check blobstore2_info first, since
    v1 is being deprecated.
    """

    INLINE = "INLINE"
    """
    Data is included into this proto buffer
    """

    BIGSTORE_REF = "BIGSTORE_REF"
    """
    Reference points to a bigstore object
    """

    COSMO_BINARY_REFERENCE = "COSMO_BINARY_REFERENCE"
    """
    Indicates the data is stored in cosmo_binary_reference.
    """


class ObjectId(BaseModel):
    """
    This is a copy of the tech.blob.ObjectId proto, which could not be used
    directly here due to transitive closure issues with JavaScript support; see
    http://b/8801763.
    """

    bucketName: Optional[str] = None
    """
    The name of the bucket to which this object belongs.
    """

    objectName: Optional[str] = None
    """
    The name of the object.
    """

    generation: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    Generation of the object. Generations are monotonically increasing across
    writes, allowing them to be be compared to determine which generation is
    newer. If this is omitted in a request, then you are requesting the live
    object. See http://go/bigstore-versions
    """


class CompositeMedia(BaseModel):
    """
    A sequence of media data references representing composite data. Introduced
    to support Bigstore composite objects. For details, visit
    http://go/bigstore-composites.
    """

    crc32cHash: Optional[int] = Field(None, ge=0, le=2**32 - 1)
    """
    uint32 format

    crc32.c hash for the payload.
    """

    path: Optional[str] = None
    """
    Path to the data, set if reference_type is PATH
    """

    objectId: Optional[ObjectId] = None
    """
    Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
    """

    blobstore2Info: Optional[Blobstore2Info] = None
    """
    Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers to
    a v2 blob.
    """

    cosmoBinaryReference: Optional[bytes] = None
    """
    A binary data reference for a media download. Serves as a
    technology-agnostic binary reference in some Google infrastructure. This
    value is a serialized storage_cosmo.BinaryReference proto. Storing it as
    bytes is a hack to get around the fact that the cosmo proto (as well as
    others it includes) doesn't support JavaScript. This prevents us from
    including the actual type of this field.
    """

    sha1Hash: Optional[bytes] = None
    """
    SHA-1 hash for the payload.
    """

    md5Hash: Optional[bytes] = None
    """
    MD5 hash for the payload.
    """

    referenceType: Optional[CompositeMediaReferenceType] = None
    """
    Describes what the field reference contains.
    """

    inline: Optional[bytes] = None
    """
    Media data, set if reference_type is INLINE
    """

    length: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    Size of the data, in bytes
    """

    blobRef: Annotated[
        Optional[bytes],
        deprecated("This item is deprecated!"),
    ] = None
    """
    Blobstore v1 reference, set if reference_type is BLOBSTORE_REF This should
    be the byte representation of a blobstore.BlobRef. Since Blobstore is
    deprecating v1, use blobstore2_info instead. For now, any v2 blob will also
    be represented in this field as v1 BlobRef.
    """


class DiffUploadRequest(BaseModel):
    """
    A Diff upload request. For details on the Scotty Diff protocol, visit
    http://go/scotty-diff-protocol.
    """

    objectVersion: Optional[str] = None
    """
    The object version of the object that is the base version the incoming diff
    script will be applied to. This field will always be filled in.
    """

    objectInfo: Optional[CompositeMedia] = None
    """
    The location of the new object. Agents must clone the object located here,
    as the upload server will delete the contents once a response is received.
    """

    checksumsInfo: Optional[CompositeMedia] = None
    """
    The location of the checksums for the new object. Agents must clone the
    object located here, as the upload server will delete the contents once a
    response is received. For details on the format of the checksums, see
    http://go/scotty-diff-protocol.
    """


class DiffUploadResponse(BaseModel):
    """
    Backend response for a Diff upload request. For details on the Scotty Diff
    protocol, visit http://go/scotty-diff-protocol.
    """

    objectVersion: Optional[str] = None
    """
    The object version of the object at the server. Must be included in the end
    notification response. The version in the end notification response must
    correspond to the new version of the object that is now stored at the
    server, after the upload.
    """

    originalObject: Optional[CompositeMedia] = None
    """
    The location of the original file for a diff upload request. Must be filled
    in if responding to an upload start notification.
    """


class ContentTypeInfo(BaseModel):
    """
    Detailed Content-Type information from Scotty. The Content-Type of the
    media will typically be filled in by the header or Scotty's best_guess, but
    this extended information provides the backend with more information so
    that it can make a better decision if needed. This is only used on media
    upload requests from Scotty.
    """

    fromFusionId: Optional[str] = None
    """
    The content type of the file detected by Fusion ID. go/fusionid
    """

    fromBytes: Optional[str] = None
    """
    The content type of the file derived by looking at specific bytes (i.e.
    "magic bytes") of the actual file.
    """

    bestGuess: Optional[str] = None
    """
    Scotty's best guess of what the content type of the file is.
    """

    fromHeader: Optional[str] = None
    """
    The content type of the file as specified in the request headers, multipart
    headers, or RUPIO start request.
    """

    fromUrlPath: Optional[str] = None
    """
    The content type of the file derived from the file extension of the URL
    path. The URL path is assumed to represent a file name (which is typically
    only true for agents that are providing a REST API).
    """

    fusionIdDetectionMetadata: Optional[bytes] = None
    """
    Metadata information from Fusion ID detection. Serialized
    FusionIdDetectionMetadata proto. Only set if from_fusion_id is set.
    """

    fromFileName: Optional[str] = None
    """
    The content type of the file derived from the file extension of the
    original file name used by the client.
    """


class DownloadParameters(BaseModel):
    """
    Parameters specific to media downloads.
    """

    ignoreRange: Optional[bool] = None
    """
    Determining whether or not Apiary should skip the inclusion of any
    Content-Range header on its response to Scotty.
    """

    allowGzipCompression: Optional[bool] = None
    """
    A boolean to be returned in the response to Scotty. Allows/disallows gzip
    encoding of the payload content when the server thinks it's advantageous
    (hence, does not guarantee compression) which allows Scotty to GZip the
    response to the client.
    """


class DiffVersionResponse(BaseModel):
    """
    Backend response for a Diff get version response. For details on the Scotty
    Diff protocol, visit http://go/scotty-diff-protocol.
    """

    objectSizeBytes: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    The total size of the server object.
    """

    objectVersion: Optional[str] = None
    """
    The version of the object stored at the server.
    """


class DiffChecksumsResponse(BaseModel):
    """
    Backend response for a Diff get checksums response. For details on the
    Scotty Diff protocol, visit http://go/scotty-diff-protocol.
    """

    objectSizeBytes: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    The total size of the server object.
    """

    checksumsLocation: Optional[CompositeMedia] = None
    """
    Exactly one of these fields must be populated. If checksums_location is
    filled, the server will return the corresponding contents to the user. If
    object_location is filled, the server will calculate the checksums based on
    the content there and return that to the user. For details on the format of
    the checksums, see http://go/scotty-diff-protocol.
    """

    objectVersion: Optional[str] = None
    """
    The object version of the object the checksums are being returned for.
    """

    chunkSizeBytes: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    The chunk size of checksums. Must be a multiple of 256KB.
    """

    objectLocation: Optional[CompositeMedia] = None
    """
    If set, calculate the checksums based on the contents and return them to
    the caller.
    """


class DiffDownloadResponse(BaseModel):
    """
    Backend response for a Diff download response. For details on the Scotty
    Diff protocol, visit http://go/scotty-diff-protocol.
    """

    objectLocation: Optional[CompositeMedia] = None
    """
    The original object location.
    """


class MediaRequestInfoNotificationType(str, Enum):
    START = "START"
    """
    Such requests signals the start of a request containing media upload. Only
    the media field(s) in the inserted/updated resource are set. The response
    should either return an error or succeed. On success, responses don't need
    to contain anything.
    """

    PROGRESS = "PROGRESS"
    """
    Such requests signals that the upload has progressed and that the backend
    might want to access the media file specified in relevant fields in the
    resource. Only the media field(s) in the inserted/updated resource are set.
    The response should either return an error or succeed. On success,
    responses don't need to contain anything.
    """

    END = "END"
    """
    Such requests signals the end of a request containing media upload. END
    should be handled just like normal Insert/Upload requests, that is, they
    should process the request and return a complete resource in the response.
    Pointers to media data (a GFS path usually) appear in the relevant fields
    in the inserted/updated resource. See gdata.Media in data.proto.
    """

    RESPONSE_SENT = "RESPONSE_SENT"
    """
    Such requests occur after an END and signal that the response has been sent
    back to the client. RESPONSE_SENT is only sent to the backend if it is
    configured to receive them. The response does not need to contain anything.
    """

    ERROR = "ERROR"
    """
    Such requests indicate that an error occurred while processing the request.
    ERROR is only sent to the backend if it is configured to receive them. It
    is not guaranteed that all errors will result in this notification to the
    backend, even if the backend requests them. Since these requests are just
    for informational purposes, the response does not need to contain anything.
    """


class MediaRequestInfo(BaseModel):
    """
    Extra information added to operations that support Scotty media requests.
    """

    notificationType: MediaRequestInfoNotificationType
    """
    The type of notification received from Scotty.
    """

    requestReceivedParamsServingInfo: Optional[bytes] = None
    """
    The partition of the Scotty server handling this request. type is
    uploader_service.RequestReceivedParamsServingInfo
    LINT.IfChange(request_received_params_serving_info_annotations)
    LINT.ThenChange()
    """

    currentBytes: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    The number of current bytes uploaded or downloaded.
    """

    physicalHeaders: Optional[bytes] = None
    """
    The physical headers provided by RequestReceivedParameters in Scotty
    request. type is uploader_service.KeyValuePairs.
    """

    requestId: Optional[str] = None
    """
    The Scotty request ID.
    """

    totalBytes: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    The total size of the file.
    """

    customData: Optional[str] = None
    """
    Data to be copied to backend requests. Custom data is returned to Scotty in
    the agent_state field, which Scotty will then provide in subsequent upload
    notifications.
    """

    totalBytesIsEstimated: Optional[bool] = None
    """
    Whether the total bytes field contains an estimated data.
    """

    diffObjectVersion: Optional[str] = None
    """
    Set if the http request info is diff encoded. The value of this field is
    the version number of the base revision. This is corresponding to Apiary's
    mediaDiffObjectVersion
    (//depot/google3/java/com/google/api/server/media/variable/DiffObjectVersionVariable.java).
    See go/esf-scotty-diff-upload for more information.
    """

    finalStatus: Optional[int] = None
    """
    int32 format

    The existence of the final_status field indicates that this is the last
    call to the agent for this request_id.
    http://google3/uploader/agent/scotty_agent.proto?l=737&rcl=347601929
    """


class Media(BaseModel):
    """
    A reference to data stored on the filesystem, on GFS or in blobstore.
    """

    contentType: Optional[str] = None
    """
    MIME type of the data
    """

    blobstore2Info: Optional[Blobstore2Info] = None
    """
    Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers to
    a v2 blob.
    """

    cosmoBinaryReference: Optional[bytes] = None
    """
    A binary data reference for a media download. Serves as a
    technology-agnostic binary reference in some Google infrastructure. This
    value is a serialized storage_cosmo.BinaryReference proto. Storing it as
    bytes is a hack to get around the fact that the cosmo proto (as well as
    others it includes) doesn't support JavaScript. This prevents us from
    including the actual type of this field.
    """

    length: Optional[str] = Field(None, pattern=r"^[+-]?\d+$")
    """
    int64 format

    Size of the data, in bytes
    """

    diffUploadRequest: Optional[DiffUploadRequest] = None
    """
    Set if reference_type is DIFF_UPLOAD_REQUEST.
    """

    diffUploadResponse: Optional[DiffUploadResponse] = None
    """
    Set if reference_type is DIFF_UPLOAD_RESPONSE.
    """

    hashVerified: Optional[bool] = None
    """
    For Scotty uploads only. If a user sends a hash code and the backend has
    requested that Scotty verify the upload against the client hash, Scotty
    will perform the check on behalf of the backend and will reject it if the
    hashes don't match. This is set to true if Scotty performed this
    verification.
    """

    compositeMedia: Optional[list[CompositeMedia]] = None
    """
    A composite media composed of one or more media objects, set if
    reference_type is COMPOSITE_MEDIA. The media length field must be set to
    the sum of the lengths of all composite media objects. Note: All composite
    media must have length specified.
    """

    contentTypeInfo: Optional[ContentTypeInfo] = None
    """
    Extended content type information provided for Scotty uploads.
    """

    downloadParameters: Optional[DownloadParameters] = None
    """
    Parameters for a media download.
    """

    objectId: Optional[ObjectId] = None
    """
    Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
    """

    sha256Hash: Optional[bytes] = None
    """
    Scotty-provided SHA256 hash for an upload.
    """

    diffVersionResponse: Optional[DiffVersionResponse] = None
    """
    Set if reference_type is DIFF_VERSION_RESPONSE.
    """

    inline: Optional[bytes] = None
    """
    Media data, set if reference_type is INLINE
    """

    diffChecksumsResponse: Optional[DiffChecksumsResponse] = None
    """
    Set if reference_type is DIFF_CHECKSUMS_RESPONSE.
    """

    token: Optional[str] = None
    """
    A unique fingerprint/version id for the media data
    """

    diffDownloadResponse: Optional[DiffDownloadResponse] = None
    """
    Set if reference_type is DIFF_DOWNLOAD_RESPONSE.
    """

    bigstoreObjectRef: Annotated[
        Optional[bytes], deprecated("This item is deprecated!")
    ] = None
    """
    Use object_id instead.
    """

    timestamp: Optional[str] = Field(None, pattern=r"^\d+$")
    """
    uint64 format

    Time at which the media data was last updated, in milliseconds since UNIX
    epoch
    """

    sha512Hash: Optional[bytes] = None
    """
    Scotty-provided SHA512 hash for an upload.
    """

    sha1Hash: Optional[bytes] = None
    """
    Scotty-provided SHA1 hash for an upload.
    """

    filename: Optional[str] = None
    """
    Original file name
    """

    isPotentialRetry: Optional[bool] = None
    """
    `is_potential_retry` is set false only when Scotty is certain that it has
    not sent the request before. When a client resumes an upload, this field
    must be set true in agent calls, because Scotty cannot be certain that it
    has never sent the request before due to potential failure in the session
    state persistence.
    """

    mediaId: Optional[bytes] = None
    """
    Media id to forward to the operation GetMedia. Can be set if reference_type
    is GET_MEDIA.
    """

    md5Hash: Optional[bytes] = None
    """
    Scotty-provided MD5 hash for an upload.
    """

    blobRef: Annotated[Optional[bytes], deprecated("This item is deprecated!")] = None
    """
    Blobstore v1 reference, set if reference_type is BLOBSTORE_REF This should
    be the byte representation of a blobstore.BlobRef. Since Blobstore is
    deprecating v1, use blobstore2_info instead. For now, any v2 blob will also
    be represented in this field as v1 BlobRef.
    """

    crc32cHash: Optional[int] = Field(None, ge=0, le=2**32 - 1)
    """
    uint32 format

    For Scotty Uploads: Scotty-provided hashes for uploads
    
    For Scotty Downloads: (WARNING: DO NOT USE WITHOUT PERMISSION FROM THE
    SCOTTY TEAM.) A Hash provided by the agent to be used to verify the data
    being downloaded. Currently only supported for inline payloads. Further,
    only crc32c_hash is currently supported.
    """

    hash: Annotated[Optional[str], deprecated("This item is deprecated!")] = None
    """
    Deprecated, use one of explicit hash type fields instead. These two hash
    related fields will only be populated on Scotty based media uploads and
    will contain the content of the hash group in the NotificationRequest:
    http://cs/#google3/blobstore2/api/scotty/service/proto/upload_listener.proto&q=class:Hash
    Hex encoded hash value of the uploaded media.
    """

    path: Optional[str] = None
    """
    Path to the data, set if reference_type is PATH
    """

    algorithm: Annotated[Optional[str], deprecated("This item is deprecated!")] = None
    """
    Deprecated, use one of explicit hash type fields instead. Algorithm used
    for calculating the hash. As of 2011/01/21, "MD5" is the only possible
    value for this field. New values may be added at any time.
    """

    referenceType: Optional[MediaReferenceType] = None
    """
    Describes what the field reference contains.
    """
